export {default as Home} from './Home'
export {default as Pricing} from './Pricing'
export {default as Sales} from './Sales'
export {default as Login} from './Login'
export {default as TeamSize} from './TeamSize'
export {default as BigTeam} from './BigTeam'
export {default as SmallTeam} from './SmallTeam'